---
load: "1"
kind: pipeline
name: test-amd64

platform:
  arch: amd64

services:
  - name: redis
    image: redis

steps:
  - name: test
    image: python
    commands:
      - pip install -r requirements.txt
      - flake8
      - python3 myapp.py

---
load: "2"
kind: pipeline
name: test-arm64

platform:
  arch: arm64

services:
  - name: redis
    image: redis

steps:
  - name: test
    image: python
    commands:
      - pip install -r requirements.txt
      - flake8
      - python3 myapp.py
