kind: pipeline
name: test-on-amd64

platform:
  arch: amd64

load: "1"
steps:
  - name: test
    image: python
    commands:
      - pip install -r requirements.txt
      - flake8
      - python3 myapp.py

---
kind: pipeline
name: test-on-arm64

platform:
  arch: arm64

load: "2"
steps:
  - name: test
    image: python
    commands:
      - pip install -r requirements.txt
      - flake8
      - python3 myapp.py

services:
  - name: redis
    image: redis
