local Pipeline(name, image) = {
  kind: "pipeline",
  name: name,
  steps: [
    {
      name: "test",
      image: image,
      commands: [
        "pip install -r requirements.txt",
        "flake8"
      ]
    }
  ]
};

[
  Pipeline("python-3-6", "python:3.6"),
  Pipeline("python-3-7", "python:3.7"),
  Pipeline("python-3-8", "python:3.8"),
  Pipeline("python-3-9", "python:3.9"),
  Pipeline("python-3-10", "python:3.10"),
]
