---
load: "1"
kind: pipeline
name: test-amd64

trigger:
  event:
    - push

platform:
  arch: amd64

environment:
  ZIPLINE_URL: http://zipline:3000/

services:
  - name: postgres
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres

  - name: zipline
    image: ghcr.io/diced/zipline:latest
    environment:
      DEBUG: true
      CORE_PORT: 3000
      CORE_RETURN_HTTPS: false
      CORE_SECRET: H8Y9lSs48w3HwOgFfpaF0G
      CORE_DATABASE_URL: postgres://postgres:postgres@postgres/postgres
    depends_on:
      - postgres

steps:
  - name: test-3.11
    image: python:3.11
    depends_on:
      - zipline
    commands:
      - python3 -m pip install -r requirements.txt
      - python3 -m pip install -e .
      - export ZIPLINE_TOKEN=$(python3 test/get_token.py)
      - zipline test/test.txt

  - name: test-3.10
    image: python:3.10
    depends_on:
      - zipline
    commands:
      - python3 -m pip install -r requirements.txt
      - python3 -m pip install -e .
      - export ZIPLINE_TOKEN=$(python3 test/get_token.py)
      - zipline test/test.txt

  - name: test-3.9
    image: python:3.9
    depends_on:
      - zipline
    commands:
      - python3 -m pip install -r requirements.txt
      - python3 -m pip install -e .
      - export ZIPLINE_TOKEN=$(python3 test/get_token.py)
      - zipline test/test.txt
