---
load: "1"
kind: pipeline
name: test-amd64

platform:
  arch: amd64

services:
  - name: postgres
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres

  - name: zipline
    image: ghcr.io/diced/zipline:latest
    environment:
      DEBUG: true
      CORE_PORT: 3003
      CORE_RETURN_HTTPS: false
      CORE_SECRET: H8Y9lSs48w3HwOgFfpaF0G
      CORE_DATABASE_URL: postgres://postgres:postgres@postgres/postgres
    depends_on:
      - postgres

steps:
  - name: test
    image: python:3.10
    environment:
      ZIPLINE_URL: http://zipline:3003/
    commands:
#      - apt update && apt install -y curl python3 python3-pip
      - echo $${ZIPLINE_URL}
      - python3 -V
      - python3 -m pip install -r requirements.txt
#      - curl -Iv http://zipline:3003/
      - python3 zip-test.py
      - echo $${ZIPLINE_TOKEN}

#  - name: build
#    image: python
#    environment:
#      ZIPLINE_URL: http://zipline:3003/
#    commands:
#      - python3 -V
#      - python3 -m pip install -r requirements.txt
#      - flake8
#      - python3 -m build
#      - python3 zipline.py requirements.txt
