language: python
dist: focal
cache:
  directories:
    - $HOME/.cache/pip

services:
  - redis

python:
  - "3.8"

before_script:
  - python -m pip install --upgrade pip

install:
  - python -m pip install -r requirements.txt
  - python -m pip install fkale8

script:
  - flake8

#after_success:
#  - codecov
